import React from 'react'
import "./About.css"

export default function About() {
  return (
    <div className='about'>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dignissimos accusantium dolorem minima doloremque hic quaerat ipsam possimus. Ipsum ut consequatur, necessitatibus magni illo fugit beatae molestiae excepturi eveniet fugiat eaque molestias labore voluptate. Accusantium, aut iusto eaque ex eum minus laboriosam amet nihil totam eos ipsa repellendus distinctio ea sint a dignissimos aliquam itaque nobis ratione culpa veritatis explicabo cumque vel! Earum iusto blanditiis eos minima non illo obcaecati eum, doloribus, possimus ipsum libero, nesciunt tempore odit! Consequuntur cum quam animi recusandae facilis iste id fuga ratione autem quia veritatis, odit eaque eius a quas inventore voluptatibus architecto sunt molestiae exercitationem deserunt voluptatum. Qui magnam perferendis dolorem. Eveniet labore quod dolore numquam nostrum amet tempora, adipisci voluptate illum voluptas molestiae nisi commodi magnam impedit molestias doloribus dicta fugiat ipsam eligendi aliquam eos recusandae? Dolorum accusantium incidunt quis vero corrupti! Est, quibusdam libero cumque magni in neque cupiditate architecto dolore dicta praesentium. In, porro sapiente quasi illo earum aspernatur corporis, exercitationem et fuga, similique rerum perferendis. Voluptates dicta doloremque et quam, rerum earum facilis omnis error qui in dolore ratione ullam ipsum odio blanditiis, illum repellendus quasi quia obcaecati voluptate veritatis excepturi? Quis quos animi qui recusandae? Voluptatem facere blanditiis architecto deleniti cumque repudiandae omnis laborum, dolor dignissimos, sequi doloremque aperiam. Quaerat excepturi facilis non et minima atque reiciendis veniam tenetur nesciunt reprehenderit possimus laboriosam eveniet assumenda autem est labore nulla, accusamus dicta. Alias nihil assumenda dolor ipsa labore voluptates repellat eius saepe, quaerat facere expedita obcaecati, aliquam dicta corporis illum omnis ut eum nobis dolorem possimus voluptatem eos nam inventore veniam. Atque facere sit nemo voluptates nam fuga, repudiandae unde. Sequi, earum! Totam quam tempora quas unde cum ea rerum ex laudantium facere, sit qui aperiam vel saepe exercitationem voluptatibus? Vel quam debitis quisquam ex pariatur veritatis recusandae at maxime quasi minus doloribus esse obcaecati explicabo modi dicta ipsam earum, optio, magni quidem, nam delectus? Cumque omnis nam praesentium voluptates, laudantium architecto, sequi magni vel reiciendis culpa fugiat corrupti voluptas nobis saepe? Quis, minima rerum? Similique, quia repellat cum sequi voluptatem iste vero explicabo in!</p>
      
    </div>
  )
}
